const Machine = {
	GET_MACHINE_REQUEST: "GET_MACHINE_REQUEST",
	GET_MACHINE_SUCCESS: "GET_MACHINE_SUCCESS",
	GET_MACHINE_FAILED: "GET_MACHINE_FAILED",
	GET_SINGLE_MACHINE_REQUEST: "GET_SINGLE_MACHINE_REQUEST",
	GET_SINGLE_MACHINE_SUCCESS: "GET_SINGLE_MACHINE_SUCCESS",
	GET_SINGLE_MACHINE_FAILED: "GET_SINGLE_MACHINE_FAILED",
	UPDATE_SINGLE_MACHINE_REQUEST: "UPDATE_SINGLE_MACHINE_REQUEST",
	UPDATE_SINGLE_MACHINE_SUCCESS: "UPDATE_SINGLE_MACHINE_SUCCESS",
	UPDATE_SINGLE_MACHINE_FAILED: "UPDATE_SINGLE_MACHINE_FAILED",
};

export default { Machine };
